version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/anuragdhingra/go-checkstyle-bot

    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run:
          name: run build
          command: |
            dep ensure -update
            go build -v
      - run:
          name: run checkstyle
          command: |
            gocheckstyle -reporter=xml -config=.gostyle 2>gostyle.xml
      - run: ./scripts/run-gocheckstyle.sh